# Terms of Service for Nauti'Cee AI

Last updated: August 31, 2025

Welcome to Nauti'Cee AI. By using our website, mobile app, or related services, you agree to the following Terms of Service.

1. **Eligibility**  
   You must be at least 13 years old to use our services.

2. **Use of Content**  
   Content generated by Nauti'Cee AI is for entertainment and educational purposes only. Do not misuse or redistribute without permission.

3. **User Conduct**  
   You agree not to use our services to:  
   - Violate any laws  
   - Upload harmful or illegal material  
   - Harass or abuse others  

4. **Intellectual Property**  
   All branding, logos, and creative assets for Nauti'Cee AI remain the property of the creator.

5. **Disclaimer**  
   Nauti'Cee AI is provided "as-is" with no warranties. We are not responsible for damages or misuse.

6. **Changes**  
   These terms may be updated from time to time. Continued use means you accept the updated terms.

If you do not agree, please stop using our services immediately.

---
Contact: nauticeethemermaid@gmail.com
